//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd", IsNullable=false)]
public partial class standings {
    
    private standingsCategoriesCategory[][] categoriesField;
    
    private string generatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("category", typeof(standingsCategoriesCategory), IsNullable=false)]
    public standingsCategoriesCategory[][] categories {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string generated {
        get {
            return this.generatedField;
        }
        set {
            this.generatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd")]
public partial class standingsCategoriesCategory {
    
    private standingsCategoriesCategoryTournament_group[] tournament_groupField;
    
    private string idField;
    
    private string nameField;
    
    private string country_codeField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tournament_group")]
    public standingsCategoriesCategoryTournament_group[] tournament_group {
        get {
            return this.tournament_groupField;
        }
        set {
            this.tournament_groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country_code {
        get {
            return this.country_codeField;
        }
        set {
            this.country_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd")]
public partial class standingsCategoriesCategoryTournament_group {
    
    private standingsCategoriesCategoryTournament_groupTournament[] tournamentField;
    
    private string idField;
    
    private string nameField;
    
    private string season_startField;
    
    private string season_endField;
    
    private string seasonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tournament")]
    public standingsCategoriesCategoryTournament_groupTournament[] tournament {
        get {
            return this.tournamentField;
        }
        set {
            this.tournamentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string season_start {
        get {
            return this.season_startField;
        }
        set {
            this.season_startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string season_end {
        get {
            return this.season_endField;
        }
        set {
            this.season_endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd")]
public partial class standingsCategoriesCategoryTournament_groupTournament {
    
    private standingsCategoriesCategoryTournament_groupTournamentTeam[] teamField;
    
    private string idField;
    
    private string nameField;
    
    private string season_idField;
    
    private string season_startField;
    
    private string season_endField;
    
    private string seasonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("team")]
    public standingsCategoriesCategoryTournament_groupTournamentTeam[] team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string season_id {
        get {
            return this.season_idField;
        }
        set {
            this.season_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string season_start {
        get {
            return this.season_startField;
        }
        set {
            this.season_startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string season_end {
        get {
            return this.season_endField;
        }
        set {
            this.season_endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd")]
public partial class standingsCategoriesCategoryTournament_groupTournamentTeam {
    
    private string idField;
    
    private string nameField;
    
    private string aliasField;
    
    private string country_codeField;
    
    private string rankField;
    
    private string winField;
    
    private string drawField;
    
    private string lossField;
    
    private string goals_forField;
    
    private string goals_againstField;
    
    private string pointsField;
    
    private string changeField;
    
    private string countryField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alias {
        get {
            return this.aliasField;
        }
        set {
            this.aliasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country_code {
        get {
            return this.country_codeField;
        }
        set {
            this.country_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string win {
        get {
            return this.winField;
        }
        set {
            this.winField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string draw {
        get {
            return this.drawField;
        }
        set {
            this.drawField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string loss {
        get {
            return this.lossField;
        }
        set {
            this.lossField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string goals_for {
        get {
            return this.goals_forField;
        }
        set {
            this.goals_forField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string goals_against {
        get {
            return this.goals_againstField;
        }
        set {
            this.goals_againstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string change {
        get {
            return this.changeField;
        }
        set {
            this.changeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://feed.elasticstats.com/schema/soccer/sr/v2/teams-standing.xsd", IsNullable=false)]
public partial class NewDataSet {
    
    private standings[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("standings")]
    public standings[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
